apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: $NS
  labels:
    app: zabbix-server
spec:
  type: NodePort
  ports:
    - port: 10051
      targetPort: 10051
  selector:
    app: zabbix-server
