apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: $NS
  labels:
    app: zabbix-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:alpine-3.4.10
        env:
        - name: DB_SERVER_HOST
          value: "$DB_SERVER_HOST"
        - name: MYSQL_USER
          value: "$MYSQL_USER"
        - name: MYSQL_PASSWORD
          value: "$MYSQL_PASSWORD"
        - name: MYSQL_DATABASE
          value: "$MYSQL_DATABASE"
