apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: $NS
  labels:
    app: zabbix-web
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: zabbix-web
